import { Reservation } from "./Reservation";

export interface Carburant {
    id?: number; // Optional if it's autogenerated by the server
    reservation: Reservation;
    kilometrageDebut: number;
    kilometrageFin: number;
    quantiteCarburantUtiliser: number;
    carburantConsome: number;
  }
  