import { Reservation } from "./Reservation";

export interface Carburant {
    id?: number; // Optional if it's autogenerated by the server
    reservation_id: number;
    kilometrageDebut: number;
    kilometrageFin: number;
    quantiteCarburantUtiliser: number;
    carburantConsome: number;
    userId :number
  }
  